package com.imgood.advancedatamonitor.assistant;

public enum AssistantSessionKind {
    NONE,
    ORDER_CANDIDATES,
    RECIPE_CANDIDATES,
    ORDER_BATCH_CANDIDATES,
    WITHDRAW_CANDIDATES,
    WITHDRAW_BATCH_CANDIDATES,
    WITHDRAW_PARTIAL_CONFIRM,
    TELEPORT_CANDIDATES,
    ITEM_COUNT_CANDIDATES,
    STORAGE_CANDIDATES
}
