/**
 * Page visual styles — orthogonal to themeColor / themeLayout / effectsLevel.
 * Controls chrome density, radius, shadow, and default chart recipe.
 */

export type PageStyle =
  | 'classic'
  | 'linear'
  | 'viz'
  | 'glass'
  | 'industrial'
  | 'soft'
  | 'terminal'
  | 'rhodes'
  | 'cupertino'
  | 'vercel'
  | 'grafana'
  | 'swiss'
  | 'yorha'
  | 'hsr'
  | 'bloomberg'
  | 'raycast'
  | 'brutal'
  | 'steam'
  | 'inkwash'
  | 'arc-reactor'
  | 'winclassic'
  | 'cyberdeck'
  | 'origami'
  | 'hexcell'
  | 'vaporwave'
  | 'broadsheet'
  | 'dmg'
  | 'liquid'
  | 'blueprint'
  | 'screentone'
  | 'arcade'
  | 'bauhaus'
  | 'obsidian'
  | 'mesh'
  | 'doomhud'
  | 'sakura'
  | 'pcb'
  | 'polaroid'
  | 'warp'
  | 'emberforge'
  | 'frostglass'
  | 'noirfilm'
  | 'emerald-circuit'
  | 'desert-terminal'
  | 'lunar'
  | 'coral-reef'
  | 'papercraft'
  | 'neon-tokyo'
  | 'medieval'
  | 'biotank'
  | 'stardust'
  | 'coppersteam'
  | 'cleanlab'
  | 'abyss'
  | 'candypop'
  | 'military'
  | 'retrocrit'
  | 'terracotta'
  | 'prism'
  | 'notion-paper'
  | 'figma-canvas'
  | 'spotify-now'
  | 'discord-guild'
  | 'netflix-stage'
  | 'github-primer'
  | 'stripe-ledger'
  | 'openai-atelier'
  | 'tesla-cockpit'
  | 'uber-dispatch'
  | 'adobe-spectrum'
  | 'airbnb-stay'
  | 'nintendo-switch'
  | 'portal-chamber'
  | 'zelda-sheikah'
  | 'valorant-spike'
  | 'persona-velvet'
  | 'genshin-teyvat'
  | 'evangelion-nerv'
  | 'ghost-shell'
  | 'hades-styx'
  | 'cyberpunk-edge'
  | 'hollow-knight'
  | 'celeste-summit'
  | 'lol-rift'
  | 'minecraft-craft'
  | 'ff14-scion'
  | 'witcher-path'
  | 'destiny-light'
  | 'overwatch-wp'
  | 'acnh-horizon'
  | 'stardew-farm'
  | 'elden-grace'
  | 'metroid-suit'
  | 'smash-blast'
  | 'terraria-torch'
  | 'ghibli-sky'
  | 'hashira-blade'
  | 'jjk-domain'
  | 'onepiece-log'
  | 'sxf-forger'
  | 'aot-survey'
  | 'sailor-crystal'
  | 'monogatari-pop'
  | 'bebop-jazz'
  | 'frieren-journey'
  | 'bocchi-stage'
  | 'meshi-feast'
  | 'nvidia-greenroom'
  | 'linear-opsdesk'
  | 'printstream-panel'
  | 'printstream-void'
  | 'printstream-pearl'
  | 'printstream-cyan'
  | 'printstream-magenta'
  | 'printstream-spectrum'
  | 'printstream-ascii'
  | 'printstream-cross'
  | 'printstream-rect'
  | 'printstream-neon'
  | 'printstream-mono'
  | 'printstream-gloss'
  | 'aura-voxel'
  | 'aura-spore'
  | 'aura-dome'
  | 'aura-sparks'
  | 'aura-bubble';

/** Per-widget / resolved chart drawing recipe ids (7 options). */
export type ChartStyle =
  | 'inherit'
  | 'classic'
  | 'viz'
  | 'minimal'
  | 'filled'
  | 'outlined'
  | 'spark';

/** Concrete chart drawing knobs (no data/interaction changes). */
export interface ChartStyleRecipe {
  strokeWidth: number;
  areaOpacity: number;
  /** When false, area polygons are omitted even if areaColor is set. */
  showArea: boolean;
  gridYs: number[];
  gridStrokeWidth: number;
  gridOpacity: number;
  pointRadius: number;
  barTopRadius: number;
  pieRadius: number;
  pieStrokeWidth: number;
  radarFillOpacity: number;
  radarRingScales: number[];
  radarStrokeWidth: number;
}

export interface PageStylePreset {
  id: PageStyle;
  cssVars: Record<string, string>;
  /** antd borderRadius override (before compact layout shrink). */
  borderRadius: number;
  /** Optional UI font-family override for antd token. */
  fontFamily?: string;
  /** Default chartStyle when widget uses inherit. */
  defaultChartStyle: Exclude<ChartStyle, 'inherit'>;
}

export const PAGE_STYLES: PageStyle[] = [
  'classic',
  'linear',
  'viz',
  'glass',
  'industrial',
  'soft',
  'terminal',
  'rhodes',
  'cupertino',
  'vercel',
  'grafana',
  'swiss',
  'yorha',
  'hsr',
  'bloomberg',
  'raycast',
  'brutal',
  'steam',
  'inkwash',
  'arc-reactor',
  'winclassic',
  'cyberdeck',
  'origami',
  'hexcell',
  'vaporwave',
  'broadsheet',
  'dmg',
  'liquid',
  'blueprint',
  'screentone',
  'arcade',
  'bauhaus',
  'obsidian',
  'mesh',
  'doomhud',
  'sakura',
  'pcb',
  'polaroid',
  'warp',
  'emberforge',
  'frostglass',
  'noirfilm',
  'emerald-circuit',
  'desert-terminal',
  'lunar',
  'coral-reef',
  'papercraft',
  'neon-tokyo',
  'medieval',
  'biotank',
  'stardust',
  'coppersteam',
  'cleanlab',
  'abyss',
  'candypop',
  'military',
  'retrocrit',
  'terracotta',
  'prism',
  'notion-paper',
  'figma-canvas',
  'spotify-now',
  'discord-guild',
  'netflix-stage',
  'github-primer',
  'stripe-ledger',
  'openai-atelier',
  'tesla-cockpit',
  'uber-dispatch',
  'adobe-spectrum',
  'airbnb-stay',
  'nintendo-switch',
  'portal-chamber',
  'zelda-sheikah',
  'valorant-spike',
  'persona-velvet',
  'genshin-teyvat',
  'evangelion-nerv',
  'ghost-shell',
  'hades-styx',
  'cyberpunk-edge',
  'hollow-knight',
  'celeste-summit',
  'lol-rift',
  'minecraft-craft',
  'ff14-scion',
  'witcher-path',
  'destiny-light',
  'overwatch-wp',
  'acnh-horizon',
  'stardew-farm',
  'elden-grace',
  'metroid-suit',
  'smash-blast',
  'terraria-torch',
  'ghibli-sky',
  'hashira-blade',
  'jjk-domain',
  'onepiece-log',
  'sxf-forger',
  'aot-survey',
  'sailor-crystal',
  'monogatari-pop',
  'bebop-jazz',
  'frieren-journey',
  'bocchi-stage',
  'meshi-feast',
  'nvidia-greenroom',
  'linear-opsdesk',
  'printstream-panel',
  'printstream-void',
  'printstream-pearl',
  'printstream-cyan',
  'printstream-magenta',
  'printstream-spectrum',
  'printstream-ascii',
  'printstream-cross',
  'printstream-rect',
  'printstream-neon',
  'printstream-mono',
  'printstream-gloss',
  'aura-voxel',
  'aura-spore',
  'aura-dome',
  'aura-sparks',
  'aura-bubble',
];

export const CHART_STYLES: ChartStyle[] = [
  'inherit',
  'classic',
  'viz',
  'minimal',
  'filled',
  'outlined',
  'spark',
];

const DEFAULT_FONT =
  "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Microsoft YaHei', 'PingFang SC', sans-serif";

const MONO_FONT =
  "'JetBrains Mono', 'SF Mono', 'Cascadia Code', 'Consolas', 'Microsoft YaHei Mono', monospace";

const AURA_SERIF_FONT =
  "Georgia, 'Times New Roman', 'Songti SC', 'SimSun', serif";

export const PAGE_STYLE_PRESETS: Record<PageStyle, PageStylePreset> = {
  classic: {
    id: 'classic',
    borderRadius: 8,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 1px 3px rgba(0,0,0,0.12)',
      '--style-shadow-hover': '0 4px 12px rgba(0,0,0,0.18)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--border)',
      '--style-nav-pad': '8px 12px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1',
    },
  },
  linear: {
    id: 'linear',
    borderRadius: 6,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '6px',
      '--style-radius-sm': '3px',
      '--style-shadow': 'none',
      '--style-shadow-hover': 'none',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--border-light)',
      '--style-nav-pad': '6px 10px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '500',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
    },
  },
  viz: {
    id: 'viz',
    borderRadius: 4,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '2px',
      '--style-shadow': '0 1px 2px rgba(0,0,0,0.08)',
      '--style-shadow-hover': '0 2px 8px rgba(0,0,0,0.14)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--border)',
      '--style-nav-pad': '8px 12px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
    },
  },
  glass: {
    id: 'glass',
    borderRadius: 12,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '12px',
      '--style-radius-sm': '8px',
      '--style-shadow': '0 8px 24px rgba(0,0,0,0.2)',
      '--style-shadow-hover': '0 12px 32px rgba(0,0,0,0.28)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.72',
      '--style-chrome-border': 'var(--border-light)',
      '--style-nav-pad': '10px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '12px',
      '--style-content-gap-scale': '1.05',
    },
  },
  industrial: {
    id: 'industrial',
    borderRadius: 2,
    fontFamily: MONO_FONT,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'none',
      '--style-shadow-hover': 'none',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--border)',
      '--style-nav-pad': '4px 8px',
      '--style-font-ui': MONO_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.75',
    },
  },
  soft: {
    id: 'soft',
    borderRadius: 16,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '16px',
      '--style-radius-sm': '10px',
      '--style-shadow': '0 4px 16px rgba(0,0,0,0.1)',
      '--style-shadow-hover': '0 8px 28px rgba(0,0,0,0.16)',
      '--style-border-width': '0px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'transparent',
      '--style-nav-pad': '10px 16px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.15',
    },
  },
  terminal: {
    id: 'terminal',
    borderRadius: 0,
    fontFamily: MONO_FONT,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'none',
      '--style-shadow-hover': 'none',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-primary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--accent-dim, var(--border))',
      '--style-nav-pad': '4px 8px',
      '--style-font-ui': MONO_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.7',
    },
  },
  /* —— Composition-level styles (pattern / chrome / hierarchy) —— */
  rhodes: {
    id: 'rhodes',
    borderRadius: 0,
    fontFamily: MONO_FONT,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'none',
      '--style-shadow-hover': '0 0 0 1px var(--accent)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.92',
      '--style-chrome-border': 'var(--accent)',
      '--style-nav-pad': '6px 10px',
      '--style-font-ui': MONO_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
    },
  },
  cupertino: {
    id: 'cupertino',
    borderRadius: 18,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '18px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 2px 16px rgba(0,0,0,0.06)',
      '--style-shadow-hover': '0 8px 28px rgba(0,0,0,0.1)',
      '--style-border-width': '0px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'transparent',
      '--style-nav-pad': '12px 18px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.45',
    },
  },
  vercel: {
    id: 'vercel',
    borderRadius: 0,
    fontFamily: DEFAULT_FONT,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'none',
      '--style-shadow-hover': 'none',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--border)',
      '--style-nav-pad': '8px 12px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '500',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1',
    },
  },
  grafana: {
    id: 'grafana',
    borderRadius: 2,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '2px',
      '--style-shadow': 'none',
      '--style-shadow-hover': 'none',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--border)',
      '--style-nav-pad': '4px 8px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.65',
    },
  },
  swiss: {
    id: 'swiss',
    borderRadius: 0,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'none',
      '--style-shadow-hover': 'none',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--text-primary)',
      '--style-nav-pad': '10px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '800',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.2',
    },
  },
  yorha: {
    id: 'yorha',
    borderRadius: 0,
    fontFamily: DEFAULT_FONT,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'none',
      '--style-shadow-hover': 'none',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.95',
      '--style-chrome-border': 'var(--accent)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '400',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
    },
  },
  hsr: {
    id: 'hsr',
    borderRadius: 16,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '16px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 0 20px var(--accent-glow)',
      '--style-shadow-hover': '0 0 32px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.88',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '10px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '8px',
      '--style-content-gap-scale': '1.1',
    },
  },
  bloomberg: {
    id: 'bloomberg',
    borderRadius: 0,
    fontFamily: MONO_FONT,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'none',
      '--style-shadow-hover': 'none',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--border)',
      '--style-nav-pad': '3px 6px',
      '--style-font-ui': MONO_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.55',
    },
  },
  raycast: {
    id: 'raycast',
    borderRadius: 14,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '14px',
      '--style-radius-sm': '10px',
      '--style-shadow': '0 12px 40px rgba(0,0,0,0.35)',
      '--style-shadow-hover': '0 16px 48px rgba(0,0,0,0.45)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.7',
      '--style-chrome-border': 'var(--border-light)',
      '--style-nav-pad': '10px 16px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '18px',
      '--style-content-gap-scale': '1.15',
    },
  },
  brutal: {
    id: 'brutal',
    borderRadius: 0,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '4px 4px 0 var(--text-primary)',
      '--style-shadow-hover': '6px 6px 0 var(--text-primary)',
      '--style-border-width': '3px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--text-primary)',
      '--style-nav-pad': '8px 12px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '900',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
    },
  },
  steam: {
    id: 'steam',
    borderRadius: 6,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '6px',
      '--style-radius-sm': '4px',
      '--style-shadow': 'inset 0 1px 0 rgba(255,255,255,0.06), 0 4px 16px rgba(0,0,0,0.35)',
      '--style-shadow-hover': 'inset 0 1px 0 rgba(255,255,255,0.1), 0 8px 24px rgba(0,0,0,0.45)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--border)',
      '--style-nav-pad': '8px 12px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.95',
    },
  },
  inkwash: {
    id: 'inkwash',
    borderRadius: 4,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '2px',
      '--style-shadow': '0 2px 12px rgba(40,30,20,0.06)',
      '--style-shadow-hover': '0 4px 20px rgba(40,30,20,0.1)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--border)',
      '--style-nav-pad': '10px 16px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '500',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.35',
    },
  },
  'arc-reactor': {
    id: 'arc-reactor',
    borderRadius: 16,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '16px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 0 16px var(--accent-glow)',
      '--style-shadow-hover': '0 0 24px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.92',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'radial',
    },
  },
  winclassic: {
    id: 'winclassic',
    borderRadius: 0,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'inset -1px -1px 0 #000, inset 1px 1px 0 #fff',
      '--style-shadow-hover': 'inset -1px -1px 0 #000, inset 1px 1px 0 #fff',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--text-primary)',
      '--style-nav-pad': '4px 8px',
      '--style-font-ui': "'MS Sans Serif', 'Segoe UI', Tahoma, sans-serif",
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'hardcut',
    },
  },
  cyberdeck: {
    id: 'cyberdeck',
    borderRadius: 0,
    fontFamily: MONO_FONT,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '4px 0 0 var(--accent)',
      '--style-shadow-hover': '6px 0 12px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.95',
      '--style-chrome-border': 'var(--accent)',
      '--style-nav-pad': '6px 10px',
      '--style-font-ui': MONO_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'glitch',
    },
  },
  origami: {
    id: 'origami',
    borderRadius: 0,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '8px 8px 0 rgba(0,0,0,0.06)',
      '--style-shadow-hover': '12px 12px 0 rgba(0,0,0,0.08)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--border)',
      '--style-nav-pad': '10px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.2',
      '--style-enter': 'fold',
    },
  },
  hexcell: {
    id: 'hexcell',
    borderRadius: 8,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '6px',
      '--style-shadow': '0 0 0 1px var(--accent-dim)',
      '--style-shadow-hover': '0 0 14px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 12px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1',
      '--style-enter': 'stagger',
    },
  },
  vaporwave: {
    id: 'vaporwave',
    borderRadius: 4,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '2px',
      '--style-shadow': '0 0 24px var(--accent-glow)',
      '--style-shadow-hover': '0 0 36px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.85',
      '--style-chrome-border': 'var(--accent)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '800',
      '--style-card-blur': '4px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'float',
    },
  },
  broadsheet: {
    id: 'broadsheet',
    borderRadius: 0,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'none',
      '--style-shadow-hover': 'none',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--text-primary)',
      '--style-nav-pad': '8px 12px',
      '--style-font-ui': "Georgia, 'Times New Roman', 'Songti SC', serif",
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.15',
      '--style-enter': 'curtain',
    },
  },
  dmg: {
    id: 'dmg',
    borderRadius: 12,
    fontFamily: MONO_FONT,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '12px',
      '--style-radius-sm': '8px',
      '--style-shadow': 'inset 0 0 0 4px #8b956d, 0 4px 0 #4a5040',
      '--style-shadow-hover': 'inset 0 0 0 4px #8b956d, 0 4px 0 #4a5040',
      '--style-border-width': '4px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '1',
      '--style-chrome-border': '#4a5040',
      '--style-nav-pad': '6px 10px',
      '--style-font-ui': MONO_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'boot',
    },
  },
  liquid: {
    id: 'liquid',
    borderRadius: 24,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '24px',
      '--style-radius-sm': '16px',
      '--style-shadow': '0 16px 48px rgba(0,0,0,0.35)',
      '--style-shadow-hover': '0 20px 56px rgba(0,0,0,0.45)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.55',
      '--style-chrome-border': 'rgba(255,255,255,0.2)',
      '--style-nav-pad': '12px 18px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '24px',
      '--style-content-gap-scale': '1.2',
      '--style-enter': 'unblur',
    },
  },
  blueprint: {
    id: 'blueprint',
    borderRadius: 0,
    fontFamily: MONO_FONT,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'none',
      '--style-shadow-hover': 'none',
      '--style-border-width': '1px',
      '--style-card-bg': 'transparent',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--accent)',
      '--style-nav-pad': '6px 10px',
      '--style-font-ui': MONO_FONT,
      '--style-title-weight': '500',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.95',
      '--style-enter': 'draw',
    },
  },
  screentone: {
    id: 'screentone',
    borderRadius: 0,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '4px 4px 0 #000',
      '--style-shadow-hover': '6px 6px 0 #000',
      '--style-border-width': '3px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': '#000',
      '--style-nav-pad': '8px 12px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '900',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1',
      '--style-enter': 'slash',
    },
  },
  arcade: {
    id: 'arcade',
    borderRadius: 8,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 0 16px var(--accent-glow), inset 0 0 20px rgba(0,0,0,0.4)',
      '--style-shadow-hover': '0 0 28px var(--accent-glow)',
      '--style-border-width': '4px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--accent)',
      '--style-nav-pad': '8px 12px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '800',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'coin',
    },
  },
  bauhaus: {
    id: 'bauhaus',
    borderRadius: 0,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'none',
      '--style-shadow-hover': 'none',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--text-primary)',
      '--style-nav-pad': '10px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '800',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'tiles',
    },
  },
  obsidian: {
    id: 'obsidian',
    borderRadius: 6,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '6px',
      '--style-radius-sm': '4px',
      '--style-shadow': 'none',
      '--style-shadow-hover': '0 2px 8px rgba(0,0,0,0.2)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--border)',
      '--style-nav-pad': '6px 12px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.95',
      '--style-enter': 'slide',
    },
  },
  mesh: {
    id: 'mesh',
    borderRadius: 20,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '20px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 8px 30px rgba(0,0,0,0.12)',
      '--style-shadow-hover': '0 12px 40px rgba(0,0,0,0.18)',
      '--style-border-width': '0px',
      '--style-card-bg': 'var(--bg-secondary)',
      '--style-card-opacity': '0.92',
      '--style-chrome-border': 'transparent',
      '--style-nav-pad': '10px 16px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.25',
      '--style-enter': 'rise',
    },
  },
  doomhud: {
    id: 'doomhud',
    borderRadius: 0,
    fontFamily: MONO_FONT,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'inset 0 0 0 1px #666',
      '--style-shadow-hover': 'inset 0 0 0 1px #a00',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '1',
      '--style-chrome-border': '#888',
      '--style-nav-pad': '4px 8px',
      '--style-font-ui': MONO_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.7',
      '--style-enter': 'slam',
    },
  },
  sakura: {
    id: 'sakura',
    borderRadius: 18,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '18px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 8px 24px rgba(232, 120, 160, 0.15)',
      '--style-shadow-hover': '0 12px 32px rgba(232, 120, 160, 0.22)',
      '--style-border-width': '0px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.95',
      '--style-chrome-border': 'transparent',
      '--style-nav-pad': '10px 16px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '500',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.3',
      '--style-enter': 'softfade',
    },
  },
  pcb: {
    id: 'pcb',
    borderRadius: 2,
    fontFamily: MONO_FONT,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': 'none',
      '--style-shadow-hover': '0 0 12px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'var(--accent)',
      '--style-nav-pad': '6px 10px',
      '--style-font-ui': MONO_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'trace',
    },
  },
  polaroid: {
    id: 'polaroid',
    borderRadius: 2,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '2px',
      '--style-shadow': '0 6px 20px rgba(0,0,0,0.15)',
      '--style-shadow-hover': '0 10px 28px rgba(0,0,0,0.2)',
      '--style-border-width': '0px',
      '--style-card-bg': '#fafafa',
      '--style-card-opacity': '1',
      '--style-chrome-border': 'transparent',
      '--style-nav-pad': '10px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.15',
      '--style-enter': 'drop',
    },
  },
  warp: {
    id: 'warp',
    borderRadius: 4,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '2px',
      '--style-shadow': '0 0 24px var(--accent-glow)',
      '--style-shadow-hover': '0 0 40px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.88',
      '--style-chrome-border': 'var(--accent)',
      '--style-nav-pad': '8px 12px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1',
      '--style-enter': 'warp',
    },
  },
  emberforge: {
    id: 'emberforge',
    borderRadius: 10,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '10px',
      '--style-radius-sm': '6px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'radial',
    },
  },
  frostglass: {
    id: 'frostglass',
    borderRadius: 14,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '14px',
      '--style-radius-sm': '10px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'fade',
    },
  },
  noirfilm: {
    id: 'noirfilm',
    borderRadius: 2,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.95',
      '--style-enter': 'hardcut',
    },
  },
  'emerald-circuit': {
    id: 'emerald-circuit',
    borderRadius: 4,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1',
      '--style-enter': 'stagger',
    },
  },
  'desert-terminal': {
    id: 'desert-terminal',
    borderRadius: 6,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '6px',
      '--style-radius-sm': '2px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'fade',
    },
  },
  lunar: {
    id: 'lunar',
    borderRadius: 12,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '12px',
      '--style-radius-sm': '8px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.15',
      '--style-enter': 'fade',
    },
  },
  'coral-reef': {
    id: 'coral-reef',
    borderRadius: 16,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '16px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'radial',
    },
  },
  papercraft: {
    id: 'papercraft',
    borderRadius: 4,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.2',
      '--style-enter': 'fold',
    },
  },
  'neon-tokyo': {
    id: 'neon-tokyo',
    borderRadius: 0,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'glitch',
    },
  },
  medieval: {
    id: 'medieval',
    borderRadius: 4,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'drop',
    },
  },
  biotank: {
    id: 'biotank',
    borderRadius: 10,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '10px',
      '--style-radius-sm': '6px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1',
      '--style-enter': 'radial',
    },
  },
  stardust: {
    id: 'stardust',
    borderRadius: 14,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '14px',
      '--style-radius-sm': '10px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'warp',
    },
  },
  coppersteam: {
    id: 'coppersteam',
    borderRadius: 6,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '6px',
      '--style-radius-sm': '2px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1',
      '--style-enter': 'fade',
    },
  },
  cleanlab: {
    id: 'cleanlab',
    borderRadius: 8,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.2',
      '--style-enter': 'fade',
    },
  },
  abyss: {
    id: 'abyss',
    borderRadius: 8,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1',
      '--style-enter': 'warp',
    },
  },
  candypop: {
    id: 'candypop',
    borderRadius: 18,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '18px',
      '--style-radius-sm': '14px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.15',
      '--style-enter': 'drop',
    },
  },
  military: {
    id: 'military',
    borderRadius: 2,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'hardcut',
    },
  },
  retrocrit: {
    id: 'retrocrit',
    borderRadius: 0,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'hardcut',
    },
  },
  terracotta: {
    id: 'terracotta',
    borderRadius: 8,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'fade',
    },
  },
  prism: {
    id: 'prism',
    borderRadius: 12,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '12px',
      '--style-radius-sm': '8px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'warp',
    },
  },
  'notion-paper': {
    id: 'notion-paper',
    borderRadius: 4,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'fade',
    },
  },
  'figma-canvas': {
    id: 'figma-canvas',
    borderRadius: 8,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'slide',
    },
  },
  'spotify-now': {
    id: 'spotify-now',
    borderRadius: 10,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '10px',
      '--style-radius-sm': '6px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'hardcut',
    },
  },
  'discord-guild': {
    id: 'discord-guild',
    borderRadius: 12,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '12px',
      '--style-radius-sm': '8px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'warp',
    },
  },
  'netflix-stage': {
    id: 'netflix-stage',
    borderRadius: 14,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '14px',
      '--style-radius-sm': '10px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'fade',
    },
  },
  'github-primer': {
    id: 'github-primer',
    borderRadius: 2,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'slide',
    },
  },
  'stripe-ledger': {
    id: 'stripe-ledger',
    borderRadius: 0,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'hardcut',
    },
  },
  'openai-atelier': {
    id: 'openai-atelier',
    borderRadius: 16,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '16px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'warp',
    },
  },
  'tesla-cockpit': {
    id: 'tesla-cockpit',
    borderRadius: 4,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'fade',
    },
  },
  'uber-dispatch': {
    id: 'uber-dispatch',
    borderRadius: 8,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'slide',
    },
  },
  'adobe-spectrum': {
    id: 'adobe-spectrum',
    borderRadius: 10,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '10px',
      '--style-radius-sm': '6px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'hardcut',
    },
  },
  'airbnb-stay': {
    id: 'airbnb-stay',
    borderRadius: 12,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '12px',
      '--style-radius-sm': '8px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'warp',
    },
  },
  'nintendo-switch': {
    id: 'nintendo-switch',
    borderRadius: 14,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '14px',
      '--style-radius-sm': '10px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'fade',
    },
  },
  'portal-chamber': {
    id: 'portal-chamber',
    borderRadius: 2,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'slide',
    },
  },
  'zelda-sheikah': {
    id: 'zelda-sheikah',
    borderRadius: 0,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'hardcut',
    },
  },
  'valorant-spike': {
    id: 'valorant-spike',
    borderRadius: 16,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '16px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'warp',
    },
  },
  'persona-velvet': {
    id: 'persona-velvet',
    borderRadius: 4,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'fade',
    },
  },
  'genshin-teyvat': {
    id: 'genshin-teyvat',
    borderRadius: 8,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'slide',
    },
  },
  'evangelion-nerv': {
    id: 'evangelion-nerv',
    borderRadius: 10,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '10px',
      '--style-radius-sm': '6px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'hardcut',
    },
  },
  'ghost-shell': {
    id: 'ghost-shell',
    borderRadius: 12,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '12px',
      '--style-radius-sm': '8px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'warp',
    },
  },
  'hades-styx': {
    id: 'hades-styx',
    borderRadius: 14,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '14px',
      '--style-radius-sm': '10px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'fade',
    },
  },
  'cyberpunk-edge': {
    id: 'cyberpunk-edge',
    borderRadius: 2,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'slide',
    },
  },
  'hollow-knight': {
    id: 'hollow-knight',
    borderRadius: 0,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'hardcut',
    },
  },
  'celeste-summit': {
    id: 'celeste-summit',
    borderRadius: 16,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '16px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'warp',
    },
  },
  'lol-rift': {
    id: 'lol-rift',
    borderRadius: 4,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'fade',
    },
  },
  'minecraft-craft': {
    id: 'minecraft-craft',
    borderRadius: 8,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'slide',
    },
  },
  'ff14-scion': {
    id: 'ff14-scion',
    borderRadius: 10,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '10px',
      '--style-radius-sm': '6px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'hardcut',
    },
  },
  'witcher-path': {
    id: 'witcher-path',
    borderRadius: 12,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '12px',
      '--style-radius-sm': '8px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'warp',
    },
  },
  'destiny-light': {
    id: 'destiny-light',
    borderRadius: 14,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '14px',
      '--style-radius-sm': '10px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'fade',
    },
  },
  'overwatch-wp': {
    id: 'overwatch-wp',
    borderRadius: 2,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'slide',
    },
  },
  'acnh-horizon': {
    id: 'acnh-horizon',
    borderRadius: 0,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'hardcut',
    },
  },
  'stardew-farm': {
    id: 'stardew-farm',
    borderRadius: 16,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '16px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'warp',
    },
  },
  'elden-grace': {
    id: 'elden-grace',
    borderRadius: 4,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'fade',
    },
  },
  'metroid-suit': {
    id: 'metroid-suit',
    borderRadius: 8,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'slide',
    },
  },
  'smash-blast': {
    id: 'smash-blast',
    borderRadius: 10,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '10px',
      '--style-radius-sm': '6px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'hardcut',
    },
  },
  'terraria-torch': {
    id: 'terraria-torch',
    borderRadius: 12,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '12px',
      '--style-radius-sm': '8px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'warp',
    },
  },
  'ghibli-sky': {
    id: 'ghibli-sky',
    borderRadius: 14,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '14px',
      '--style-radius-sm': '10px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'fade',
    },
  },
  'hashira-blade': {
    id: 'hashira-blade',
    borderRadius: 2,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'slide',
    },
  },
  'jjk-domain': {
    id: 'jjk-domain',
    borderRadius: 0,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'hardcut',
    },
  },
  'onepiece-log': {
    id: 'onepiece-log',
    borderRadius: 16,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '16px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'warp',
    },
  },
  'sxf-forger': {
    id: 'sxf-forger',
    borderRadius: 4,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'fade',
    },
  },
  'aot-survey': {
    id: 'aot-survey',
    borderRadius: 8,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'slide',
    },
  },
  'sailor-crystal': {
    id: 'sailor-crystal',
    borderRadius: 10,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '10px',
      '--style-radius-sm': '6px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'hardcut',
    },
  },
  'monogatari-pop': {
    id: 'monogatari-pop',
    borderRadius: 12,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '12px',
      '--style-radius-sm': '8px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'warp',
    },
  },
  'bebop-jazz': {
    id: 'bebop-jazz',
    borderRadius: 14,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '14px',
      '--style-radius-sm': '10px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'fade',
    },
  },
  'frieren-journey': {
    id: 'frieren-journey',
    borderRadius: 2,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'slide',
    },
  },
  'bocchi-stage': {
    id: 'bocchi-stage',
    borderRadius: 0,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'hardcut',
    },
  },
  'meshi-feast': {
    id: 'meshi-feast',
    borderRadius: 16,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '16px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'warp',
    },
  },
  'nvidia-greenroom': {
    id: 'nvidia-greenroom',
    borderRadius: 4,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.1',
      '--style-enter': 'fade',
    },
  },
  'linear-opsdesk': {
    id: 'linear-opsdesk',
    borderRadius: 8,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.94',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.85',
      '--style-enter': 'slide',
    },
  },
  'printstream-panel': {
    id: 'printstream-panel',
    borderRadius: 2,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'ascii-wipe',
    },
  },
  'printstream-void': {
    id: 'printstream-void',
    borderRadius: 0,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'hardcut',
    },
  },
  'printstream-pearl': {
    id: 'printstream-pearl',
    borderRadius: 4,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '2px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'pearl-fade',
    },
  },
  'printstream-cyan': {
    id: 'printstream-cyan',
    borderRadius: 2,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'pearl-fade',
    },
  },
  'printstream-magenta': {
    id: 'printstream-magenta',
    borderRadius: 2,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.95',
      '--style-enter': 'slash',
    },
  },
  'printstream-spectrum': {
    id: 'printstream-spectrum',
    borderRadius: 4,
    defaultChartStyle: 'spark',
    cssVars: {
      '--style-radius': '4px',
      '--style-radius-sm': '2px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'warp',
    },
  },
  'printstream-ascii': {
    id: 'printstream-ascii',
    borderRadius: 0,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.9',
      '--style-enter': 'ascii-wipe',
    },
  },
  'printstream-cross': {
    id: 'printstream-cross',
    borderRadius: 0,
    defaultChartStyle: 'classic',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'hardcut',
    },
  },
  'printstream-rect': {
    id: 'printstream-rect',
    borderRadius: 0,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '0.95',
      '--style-enter': 'tiles',
    },
  },
  'printstream-neon': {
    id: 'printstream-neon',
    borderRadius: 2,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '2px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'glitch',
    },
  },
  'printstream-mono': {
    id: 'printstream-mono',
    borderRadius: 0,
    defaultChartStyle: 'minimal',
    cssVars: {
      '--style-radius': '0px',
      '--style-radius-sm': '0px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'hardcut',
    },
  },
  'printstream-gloss': {
    id: 'printstream-gloss',
    borderRadius: 6,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '6px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 4px 16px var(--accent-glow)',
      '--style-shadow-hover': '0 6px 22px var(--accent-glow)',
      '--style-border-width': '2px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.96',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '700',
      '--style-card-blur': '0px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'pearl-fade',
    },
  },
  'aura-voxel': {
    id: 'aura-voxel',
    borderRadius: 20,
    fontFamily: AURA_SERIF_FONT,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '20px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 10px 40px rgba(0, 0, 0, 0.45)',
      '--style-shadow-hover': '0 14px 48px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.85',
      '--style-chrome-border': 'rgba(255, 255, 255, 0.08)',
      '--style-nav-pad': '10px 16px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '400',
      '--style-card-blur': '20px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'voxel-rise',
    },
  },
  'aura-spore': {
    id: 'aura-spore',
    borderRadius: 16,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '16px',
      '--style-radius-sm': '10px',
      '--style-shadow': '0 8px 32px rgba(0, 0, 0, 0.4)',
      '--style-shadow-hover': '0 12px 40px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.82',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '10px 16px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '500',
      '--style-card-blur': '16px',
      '--style-content-gap-scale': '1.0',
      '--style-enter': 'spore-drift',
    },
  },
  'aura-dome': {
    id: 'aura-dome',
    borderRadius: 18,
    defaultChartStyle: 'viz',
    cssVars: {
      '--style-radius': '18px',
      '--style-radius-sm': '12px',
      '--style-shadow': '0 8px 36px rgba(0, 0, 0, 0.42)',
      '--style-shadow-hover': '0 12px 44px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.82',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '10px 16px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '500',
      '--style-card-blur': '18px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'dome-fade',
    },
  },
  'aura-sparks': {
    id: 'aura-sparks',
    borderRadius: 8,
    fontFamily: MONO_FONT,
    defaultChartStyle: 'outlined',
    cssVars: {
      '--style-radius': '8px',
      '--style-radius-sm': '4px',
      '--style-shadow': '0 0 24px var(--accent-glow)',
      '--style-shadow-hover': '0 0 36px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.88',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '8px 14px',
      '--style-font-ui': MONO_FONT,
      '--style-title-weight': '600',
      '--style-card-blur': '8px',
      '--style-content-gap-scale': '0.95',
      '--style-enter': 'spark-slash',
    },
  },
  'aura-bubble': {
    id: 'aura-bubble',
    borderRadius: 20,
    defaultChartStyle: 'filled',
    cssVars: {
      '--style-radius': '20px',
      '--style-radius-sm': '14px',
      '--style-shadow': '0 10px 36px rgba(0, 0, 0, 0.4)',
      '--style-shadow-hover': '0 14px 48px var(--accent-glow)',
      '--style-border-width': '1px',
      '--style-card-bg': 'var(--bg-card)',
      '--style-card-opacity': '0.8',
      '--style-chrome-border': 'var(--accent-dim)',
      '--style-nav-pad': '10px 16px',
      '--style-font-ui': DEFAULT_FONT,
      '--style-title-weight': '500',
      '--style-card-blur': '20px',
      '--style-content-gap-scale': '1.05',
      '--style-enter': 'bubble-rise',
    },
  },
};

export const CHART_STYLE_RECIPES: Record<Exclude<ChartStyle, 'inherit'>, ChartStyleRecipe> = {
  classic: {
    strokeWidth: 1.5,
    areaOpacity: 0.3,
    showArea: true,
    gridYs: [20, 40, 60, 80],
    gridStrokeWidth: 0.3,
    gridOpacity: 0.5,
    pointRadius: 1.8,
    barTopRadius: 4,
    pieRadius: 15.9,
    pieStrokeWidth: 6,
    radarFillOpacity: 0.2,
    radarRingScales: [0.25, 0.5, 0.75, 1],
    radarStrokeWidth: 1,
  },
  viz: {
    strokeWidth: 2,
    areaOpacity: 0.18,
    showArea: true,
    gridYs: [10, 25, 40, 55, 70, 85],
    gridStrokeWidth: 0.35,
    gridOpacity: 0.65,
    pointRadius: 2.2,
    barTopRadius: 2,
    pieRadius: 16.5,
    pieStrokeWidth: 5,
    radarFillOpacity: 0.25,
    radarRingScales: [0.2, 0.4, 0.6, 0.8, 1],
    radarStrokeWidth: 1.4,
  },
  minimal: {
    strokeWidth: 1.2,
    areaOpacity: 0,
    showArea: false,
    gridYs: [],
    gridStrokeWidth: 0,
    gridOpacity: 0,
    pointRadius: 1.4,
    barTopRadius: 0,
    pieRadius: 15.9,
    pieStrokeWidth: 4,
    radarFillOpacity: 0.08,
    radarRingScales: [0.5, 1],
    radarStrokeWidth: 0.8,
  },
  filled: {
    strokeWidth: 1.2,
    areaOpacity: 0.45,
    showArea: true,
    gridYs: [25, 50, 75],
    gridStrokeWidth: 0.25,
    gridOpacity: 0.35,
    pointRadius: 1.6,
    barTopRadius: 6,
    pieRadius: 14.5,
    pieStrokeWidth: 8,
    radarFillOpacity: 0.35,
    radarRingScales: [0.33, 0.66, 1],
    radarStrokeWidth: 1,
  },
  outlined: {
    strokeWidth: 2,
    areaOpacity: 0,
    showArea: false,
    gridYs: [20, 40, 60, 80],
    gridStrokeWidth: 0.4,
    gridOpacity: 0.4,
    pointRadius: 0,
    barTopRadius: 0,
    pieRadius: 16.5,
    pieStrokeWidth: 3,
    radarFillOpacity: 0,
    radarRingScales: [0.25, 0.5, 0.75, 1],
    radarStrokeWidth: 1.5,
  },
  spark: {
    strokeWidth: 1,
    areaOpacity: 0.15,
    showArea: true,
    gridYs: [],
    gridStrokeWidth: 0,
    gridOpacity: 0,
    pointRadius: 0,
    barTopRadius: 1,
    pieRadius: 15,
    pieStrokeWidth: 5,
    radarFillOpacity: 0.15,
    radarRingScales: [1],
    radarStrokeWidth: 0.8,
  },
};

export function isPageStyle(value: string | null | undefined): value is PageStyle {
  return !!value && (PAGE_STYLES as string[]).includes(value);
}

export function isChartStyle(value: string | null | undefined): value is ChartStyle {
  return !!value && (CHART_STYLES as string[]).includes(value);
}

const LEGACY_PAGE_STYLE_ALIASES: Record<string, PageStyle> = {
  'qinghua-porcelain': 'printstream-panel',
  'yunjin-brocade': 'printstream-void',
  'batik-resist': 'printstream-pearl',
  'shibori-tie': 'printstream-cyan',
  'seigaiha-waves': 'printstream-magenta',
  'asanoha-hemp': 'printstream-spectrum',
  'ichimatsu-check': 'printstream-ascii',
  'paisley-vine': 'printstream-cross',
  'damask-court': 'printstream-rect',
  'liberty-floral': 'printstream-neon',
  'kente-rhythm': 'printstream-mono',
  'uroko-scale': 'printstream-gloss'
};

export function resolvePageStyle(value: string | null | undefined): PageStyle {
  if (isPageStyle(value)) return value;
  if (value && LEGACY_PAGE_STYLE_ALIASES[value]) return LEGACY_PAGE_STYLE_ALIASES[value];
  return 'classic';
}

/**
 * Map pageStyle → concrete chart recipe when widget chartStyle is inherit.
 */
export function chartStyleFromPageStyle(pageStyle: PageStyle): Exclude<ChartStyle, 'inherit'> {
  return PAGE_STYLE_PRESETS[pageStyle].defaultChartStyle;
}

export function getChartStyleRecipe(
  chartStyle: Exclude<ChartStyle, 'inherit'>
): ChartStyleRecipe {
  return CHART_STYLE_RECIPES[chartStyle];
}
